[package]
name = "nn-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
"num" = "*"
"rand" = "*"
"nannou" = "*"
"nalgebra" = { version="*", features=["serde-serialize", "rand", "matrixmultiply"] }
"serde" = { deatures=["derive"], version = "*" }
"serde_derive" = "*"
"serde_json" = "*"